deploy:
  name: Deploy
  runs-on: ubuntu-latest
  if: github.event_name == 'push' && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/dev')
  env:
    HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

  steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Set QA Environment
      run: echo "::set-env name=ENVIRONMENT::qa"

    - name: Set Production Environment
      if: github.ref == 'refs/heads/master'
      run: echo "::set-env name=ENVIRONMENT::prod"

    - name: Push to Heroku
      run: git push --force https://heroku:$HEROKU_API_KEY@git.heroku.com/my-app-name-$ENVIRONMENT.git $GITHUB_SHA:master

    - name: Run Database Migrations
      run: heroku run knex migrate:latest --app my-app-name-$ENVIRONMENT
